apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: brum
  name: brum
  namespace: brum

spec:
  ingresses:
    - https://brum.intern.dev.nav.no
  image: {{image}}
  port: 3000
  prometheus:
    enabled: true
    path: "/api/metrics"
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true     
  accessPolicy:
    outbound:
      rules:
        - application: brum-api
        - application: brum
          namespace: brum
  tokenx:
    enabled: true

