apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: brum
  name: brum
  namespace: brum
  annotations:
    texas.nais.io/enabled: "true"

spec:
  ingresses:
    - https://brum.intern.dev.nav.no
  image: {{image}}
  port: 3000
  prometheus:
    enabled: true
    path: "/api/metrics"
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true     
  env:
    - name: BRUM_API_URL
      value: http://brum-api.brum:8080
    - name: BACKEND_AUDIENCE
      value: api://dev-gcp.brum.brum-api/.default

  accessPolicy:
    outbound:
      rules:
        - application: brum-api
        - application: brum
          namespace: brum