name: Build & Deploy frontend for brum
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-dev:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: false
      - name: Build and push docker image to GAR
        uses: nais/docker-build-push@main
        id: docker-push
        with:
          target: runtime
          team: brum
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          RESOURCE: dev.yml
  build-prod:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: false
      - name: Build and push docker image to GAR
        uses: nais/docker-build-push@main
        id: docker-push
        with:
          target: runtime
          team: brum
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          RESOURCE: prod.yml        
